### ISSUE TITLE
Security error when cloning repo on step 5

### ISSUE THREAD

**Issue by ewhitley** [microsoft-healthcare-madison/demo-auc-app#6]
Page: https://microsoft-healthcare-madison.github.io/demo-auc-app/#5

6. Getting Started
 -> Clone 1.0

``
git clone --branch v1.0 git@github.com:microsoft-healthcare-madison/demo-auc-app.git
``

Gives me the following message:

``
Cloning into 'demo-auc-app'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
``

I resolved by just removing the ``git@`` to clone the repo anonymously.

**Comment by barabo** [comment]
Thanks for the issue report!

I believe the issue is that the provided command assumes you already have an ssh key associated with your github identity.  If you change the `git clone` command to use `https://github.com/microsoft-healthcare-madison/demo-auc-app.git` instead of `git@github.com:microsoft-healthcare-madison/demo-auc-app.git` it should work.

I'm planning to update the codelab to use the anonymous checkout, thanks!

**Comment by barabo** [comment]
Fixed in PR: https://github.com/microsoft-healthcare-madison/demo-auc-app/pull/7
